sudo: required
language: node_js
node_js:
  - "node"

before_install:
  - cd lz_test_lib

before_deploy:
  - yarn version --patch

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    branch: production
